### PR TITLE
shared/sync: httpgroup

### PR DESCRIPTION
**Pull request by amery**
error group for http.Server

### CODE REVIEW

**Comment by amery** [comment]
refactored for go1.18 support

**Review by karasz — CHANGES_REQUESTED** [review]
I think we can agree that we do not need to support a go version that Google does not support. We should support at most the same as they do: last two major versions released which now is 1.19 and 1.20

**Review by karasz — APPROVED** [review]

**Comment by amery** [comment]
> I think we can agree that we do not need to support a go version that Google does not support. We should support at most the same as they do: last two major versions released which now is 1.19 and 1.20

I'll make a PR switching to 1.19

**Comment by amery** [comment]
`shared/v0.1.7` tagged

**Pull request merged**
