### PR TITLE
agent: update dependencies

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Comment by karasz** [comment]
I think we should wait with this a bit to see what will quick-go do in the end, they broke a lot of projects with the release and blaming it on the go get system is not a solution nor is it productive.

**Comment by amery** [comment]
`go get github.com/quic-go/qtls-go1-20@v0.2.2` on `darvaza/agent` might solve this @karasz 

I'll try making a multi-version go builder as we also need to add 1.21 testing

**Comment by amery** [comment]
awesome!

**Comment by amery** [comment]
`agent/v0.2.3` tagged

**Pull request merged**
