### PR TITLE
shared/net: introduce AddrPort() helper

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Review by karasz — CHANGES_REQUESTED** [review]
please enable back revive after the function name and if possible a comment of why the disable is needed would be nice

**Comment by amery** [comment]
commit amended accordingly. I had neglected the `revive:enable` because it was the last function. but that can change inadvertently

**Review by karasz — APPROVED** [review]
LGTM

**Comment by amery** [comment]
`shared/v0.1.2` tagged

**Pull request merged**
