### PR TITLE
shared: fix revive grievances except cognitive-complexity

### PR DESCRIPTION
**Pull request by karasz**

### CODE REVIEW

**Comment by amery** [comment]
why not just using a Boolean as content of the maps instead of making a pretend holder struct? @karasz

**Comment by karasz** [comment]
an empty struct occupies is zero space, a boolean occupies some space (albeit it is negligible indeed)

**Comment by amery** [comment]
> an empty struct occupies is zero space, a boolean occupies some space (albeit it is negligible indeed) @amery 

`case m[k]:` is nice 😅

**Comment by karasz** [comment]
```case m[k]: ``` ???

**Comment by amery** [comment]
> ```case m[k]: ``` ???

with map[T]bool switch cases work out of the box, but not when using struct{}.
if v, ok := m[k]; ok {} begs for logic if chains 😅

**Comment by karasz** [comment]
> > `case m[k]: ` ???
> 
> with map[T]bool switch cases work out of the box, but not when using struct{}. if v, ok := m[k]; ok {} begs for logic if chains sweat_smile

uh.

**Pull request merged**
