### PR TITLE
shared/x509utils: Introduce WriteKey/WriteCert helpers

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Review by karasz — CHANGES_REQUESTED** [review]
Please put the writer first in the inputs and name the outputs

**Comment by amery** [comment]
@karasz updated accordingly. changes to `go.mod` are a by-product of `make build`

**Comment by amery** [comment]
`shared/v0.4.8` tagged

**Comment by amery** [comment]
mistagged, `shared/v0.4.9` now

**Pull request merged**
