### PR TITLE
shared/config/expand: introduce module to expand shell-style variables

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Review by karasz — CHANGES_REQUESTED** [review]
Please do not disable revive. 
s/Expand/From// in the function names.
They will become `expand.FromString` which is not ideal but not awful either.

**Comment by amery** [comment]
> Please do not disable revive.

it was only the rule complaining about expand/ExpandFoo

**Comment by amery** [comment]
@karasz amended to use `expand.FromFoo` instead of `expand.ExpandFoo` as requested

**Review by karasz — APPROVED** [review]
LGTM

**Pull request merged**
